[package]
name = "ws-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dotenv = "0.15.0"
env_logger = "0.11.8"
futures = "0.3.31"
futures-util = "0.3.31"
log = "0.4.27"
tokio = { version = "1.45.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
